name: ketemaa
description: Ketemaa.

publish_to: 'none'

version: 1.2.8+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  dartz: ^0.10.0
  equatable: ^2.0.3
  carousel_slider: ^4.0.0
  data_connection_checker: ^0.3.4
  # http: ^0.13.4
  google_fonts: ^2.1.0
  flutter_svg: any
  lint: ^1.5.3
  flutter_image_slider: ^0.0.2
  fluttertoast: ^8.0.8
  ##firebase_crashlytics: ^2.3.0
  email_validator: ^2.0.1
  bottom_bar_page_transition: ^2.0.0
  graphql_flutter: ^5.0.0
  loading_indicator: ^3.0.2
  shared_preferences: ^2.0.8
  dropdown_plus: ^0.0.9
  shimmer:
  firebase_core: ^1.14.1
  firebase_remote_config: ^2.0.4
  skeleton_animation: ^0.1.4
  provider: ^6.0.2
  another_flushbar: ^1.10.29
  store_redirect: ^2.0.1
  image_picker: ^0.8.4+9
  animated_theme_switcher: ^2.0.6
  anim_search_bar: ^2.0.2
  flutter_typeahead: ^3.2.4
  animate_do: ^2.1.0
  glass_kit: ^2.0.1
  filter_list: ^1.0.1
  flutter_initicon: ^2.0.0
  random_color: ^1.0.6-nullsafety
  hexcolor: ^2.0.6
  pinput: ^2.2.4
  blurrycontainer: ^0.1.0
  file_picker: ^4.5.1
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^19.4.56
  dropdown_button2: ^1.2.2
  url_launcher: ^6.0.20
  swipeable_tile: ^1.0.0+6
  internet_connection_checker: ^0.0.1+3
  html: ^0.15.0
  package_info_plus: ^1.4.2
  introduction_screen: ^3.0.2
  community_material_icon: ^5.9.55
  firebase_messaging: ^11.4.0
  platform_device_id: ^1.0.1
  flutter_local_notifications: ^9.5.3+1
  font_awesome_flutter: ^10.1.0
  connectivity_plus: ^2.3.0
  google_sign_in: ^5.3.2
  flutter_screenutil: ^5.5.3+2
  badges: ^2.0.3
  upgrader: ^4.2.1
  cached_network_image: ^3.0.0
  app_upgrade_flutter_sdk: ^1.0.2
  image_cropper: ^2.0.3
  auto_size_text: ^3.0.0
  sign_in_with_apple: ^4.1.0
  in_app_review: ^2.0.4
  store_checker: ^1.1.0
  marquee: ^2.2.0
  syncfusion_flutter_sliders: ^19.4.56
  flutter_swipe_action_cell: ^3.0.4
  flutter_switch: ^0.3.2
  swipeable_card_stack: ^0.0.5
  flutter_dynamic_icon: ^2.1.0
#  share_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/media/logo/new_logo.png"
  adaptive_icon_background: "#1F273E"
  adaptive_icon_foreground: "assets/media/logo/new_logo.png"

  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/media/image/
    - assets/media/icon/
    - assets/media/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/media/font/Inter.ttf




